### ISSUE TITLE
missing python notebook

### ISSUE THREAD

**Issue by espinielli** [marcosmaximo/prc-challenge-ita#2]
The [README mentions `eda-v20.ipynb`](https://github.com/PRC-Data-Challenge-2024/team_tiny_rainbow?tab=readme-ov-file#neural-networks) which is not present in the repo.
Also mentioned but not present `catboost-v20.ipynb`.
Of course they are in previous commits than the latest...

**Comment by marcosmaximo** [comment]
We renamed eda-v20.ipynb to feature_engineering.ipynb, and catboost-v20.ipynb to just catboost.ipynb. Our intention was to make things easier to understand. However, we forgot to updated the names in the README.md.

**Comment by Gabrui** [comment]
Fixed by [#e16499bdf05ad4369b35c8abe22c31b437c064ce #](https://github.com/marcosmaximo/prc-challenge-ita/commit/e16499bdf05ad4369b35c8abe22c31b437c064ce)
