### ISSUE TITLE
clarification: ensemble seems to use only subset of methods described in README

### ISSUE THREAD

**Issue by espinielli** [marcosmaximo/prc-challenge-ita#3]
the code in `csv_ensemble.ipynb` states in the **Loading data** section

```python
models = ['catboost', 'xgboost', 'lightgbm']#, 'mlp', 'saint']
```
The README states that all the model have been combined but from the line above
it seems only some of them have been used for the last submission, is that the case?

**Comment by Gabrui** [comment]
Yes, the mlp and saint models had a much higher error than the other methods, and when included, their learned weights were very close to zero (<1e-10), so their influence was negligible.
